import { Html, Head, Main, NextScript } from 'next/document';


export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Dragon Reply</title>
        <meta name="description" content="generated by next app" />
        <link rel="shortcut icon" href="/dragon.png" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
